const tools=[
["JSON Formatter","Developer","Format and validate JSON","{}"],["JSON → CSV","Developer","Convert JSON arrays to CSV","CSV"],["Base64 Encoder","Developer","Encode and decode Base64","64"],["URL Encoder","Developer","Encode and decode URLs","URL"],["UUID Generator","Developer","Generate random UUIDs","ID"],["QR Generator","Utilities","Create a QR code","QR"],["Color Picker","Design","Pick and inspect colors","HEX"],["Color Converter","Design","Convert HEX, RGB and HSL","RGB"],["Timestamp Converter","Developer","Convert Unix timestamps and dates","TS"],["Regex Tester","Developer","Test regular expressions","RX"],["Markdown Preview","Writing","Preview basic Markdown","MD"],["Text Diff","Writing","Compare two texts","DIFF"],["Word Counter","Writing","Count words and characters","123"],["Image Compressor","Images","Compress an image in your browser","IMG"],["Password Generator","Security","Generate a random password","PW"],["Hash Generator","Security","Create SHA-256 hashes","SHA"],["JWT Decoder","Developer","Decode JWT header and payload","JWT"],["IP/Subnet Calculator","Network","Calculate IPv4 subnet details","IP"],["Cron Expression Helper","Developer","Explain common cron fields","CRON"]
];
const $=s=>document.querySelector(s),grid=$("#tools"),cats=$("#categories"),modal=$("#modal"),view=$("#toolView");
const esc=s=>String(s||"").replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]});
let active="All";
const categories=["All"].concat([...new Set(tools.map(function(t){return t[1]}))]);
cats.innerHTML=categories.map(function(c){return '<button class="cat '+(c==="All"?"active":"")+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>'}).join("");
function render(){const q=$("#search").value.toLowerCase();grid.innerHTML=tools.filter(function(t){return (active==="All"||t[1]===active)&&[t[0],t[1],t[2]].join(" ").toLowerCase().includes(q)}).map(function(t){return '<article class="tool" data-i="'+tools.indexOf(t)+'"><div class="tool-icon">'+t[3]+'</div><h3>'+esc(t[0])+'</h3><p>'+esc(t[2])+'</p><span class="tag">'+esc(t[1])+'</span></article>'}).join("")||"<p>No tools found.</p>"}
cats.onclick=function(e){if(!e.target.matches(".cat"))return;active=e.target.dataset.cat;document.querySelectorAll(".cat").forEach(function(x){x.classList.toggle("active",x===e.target)});render()};
$("#search").oninput=render;
document.addEventListener("keydown",function(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search").focus()}if(e.key==="Escape")closeModal()});
grid.onclick=function(e){const c=e.target.closest(".tool");if(c)openTool(+c.dataset.i)};
function field(label,id,tag,extra){tag=tag||"input";return '<div class="field"><label>'+label+'</label><'+tag+' id="'+id+'" '+(extra||"")+'></'+tag+'></div>'}
function shell(title,desc,body){return '<div class="tool-view"><h2>'+title+'</h2><p class="sub">'+desc+'</p>'+body+'</div>'}
function openTool(i){const t=tools[i],n=t[0],d=t[2];let h="";
if(n==="JSON Formatter")h=shell(n,d,field("JSON","a","textarea",'placeholder="Paste JSON here..."')+'<button class="btn" onclick="jsonFormat()">Format</button><div id="out" class="output"></div>');
else if(n==="JSON → CSV")h=shell(n,d,field("JSON array","a","textarea",'placeholder="[{&quot;name&quot;:&quot;Redro&quot;}]&quot;')+'<button class="btn" onclick="jsonCsv()">Convert</button><div id="out" class="output"></div>');
else if(n==="Base64 Encoder")h=shell(n,d,field("Text","a","textarea")+'<div class="row"><button class="btn" onclick="b64(true)">Encode</button><button class="btn secondary" onclick="b64(false)">Decode</button></div><div id="out" class="output"></div>');
else if(n==="URL Encoder")h=shell(n,d,field("Text","a","textarea")+'<div class="row"><button class="btn" onclick="urlx(true)">Encode</button><button class="btn secondary" onclick="urlx(false)">Decode</button></div><div id="out" class="output"></div>');
else if(n==="UUID Generator")h=shell(n,d,'<button class="btn" onclick="uuid()">Generate UUID</button><div id="out" class="output"></div>');
else if(n==="QR Generator")h=shell(n,d,field("Text or URL","a")+ '<button class="btn" onclick="qr()">Generate</button><div id="out" class="output"></div>');
else if(n==="Color Picker")h=shell(n,d,'<div class="field"><input id="a" type="color" value="#e11d48"></div><div id="out" class="output"></div>');
else if(n==="Color Converter")h=shell(n,d,field("HEX","a","input",'value="#e11d48"')+'<button class="btn" onclick="color()">Convert</button><div id="out" class="output"></div>');
else if(n==="Timestamp Converter")h=shell(n,d,field("Timestamp or date","a")+ '<button class="btn" onclick="timestamp()">Convert</button><div id="out" class="output"></div>');
else if(n==="Regex Tester")h=shell(n,d,field("Regex","a")+field("Test text","b","textarea")+'<button class="btn" onclick="regex()">Test</button><div id="out" class="output"></div>');
else if(n==="Markdown Preview")h=shell(n,d,field("Markdown","a","textarea")+'<button class="btn" onclick="md()">Preview</button><div id="out" class="markdown"></div>');
else if(n==="Text Diff")h=shell(n,d,field("Text A","a","textarea")+field("Text B","b","textarea")+'<button class="btn" onclick="diff()">Compare</button><div id="out" class="output"></div>');
else if(n==="Word Counter")h=shell(n,d,field("Text","a","textarea")+'<button class="btn" onclick="count()">Count</button><div id="out" class="output"></div>');
else if(n==="Image Compressor")h=shell(n,d,'<div class="field"><label>Image</label><input id="a" type="file" accept="image/*"></div><div class="field"><label>Quality</label><input id="q" type="range" min=".1" max="1" step=".1" value=".7"></div><button class="btn" onclick="compress()">Compress</button><div id="out" class="output"></div>');
else if(n==="Password Generator")h=shell(n,d,'<div class="field"><label>Length</label><input id="a" type="number" min="4" max="128" value="20"></div><button class="btn" onclick="password()">Generate</button><div id="out" class="output"></div>');
else if(n==="Hash Generator")h=shell(n,d,field("Text","a","textarea")+'<button class="btn" onclick="hash()">SHA-256</button><div id="out" class="output"></div>');
else if(n==="JWT Decoder")h=shell(n,d,field("JWT","a","textarea")+'<button class="btn" onclick="jwt()">Decode</button><div id="out" class="output"></div>');
else if(n==="IP/Subnet Calculator")h=shell(n,d,field("IPv4/CIDR","a")+ '<button class="btn" onclick="ipcalc()">Calculate</button><div id="out" class="output"></div>');
else if(n==="Cron Expression Helper")h=shell(n,d,field("Cron","a")+ '<button class="btn" onclick="cron()">Explain</button><div id="out" class="output"></div>');
view.innerHTML=h;modal.classList.add("open");if(n==="Color Picker")$("#a").oninput=function(){out(this.value)};
}
function closeModal(){modal.classList.remove("open")}$("#close").onclick=closeModal;modal.onclick=function(e){if(e.target===modal)closeModal()};
function out(x){$("#out").textContent=x}
function jsonFormat(){try{out(JSON.stringify(JSON.parse($("#a").value),null,2))}catch(e){out("Invalid JSON: "+e.message)}}
function jsonCsv(){try{const a=JSON.parse($("#a").value);if(!Array.isArray(a)||!a.length)throw Error("Expected a non-empty array");const k=[...new Set(a.flatMap(function(x){return Object.keys(x)}))];out([k.join(","),...a.map(function(x){return k.map(function(y){return '"'+String(x[y]??"").replaceAll('"','""')+'"'}).join(",")})].join("\n"))}catch(e){out("Invalid input: "+e.message)}}
function b64(enc){try{out(enc?btoa(unescape(encodeURIComponent($("#a").value))):decodeURIComponent(escape(atob($("#a").value))))}catch(e){out("Invalid Base64")}}
function urlx(enc){try{out(enc?encodeURIComponent($("#a").value):decodeURIComponent($("#a").value))}catch(e){out("Invalid encoded URL")}}
function uuid(){out(crypto.randomUUID())}
function qr(){const v=encodeURIComponent($("#a").value);$("#out").innerHTML='<img alt="QR code" width="260" height="260" src="https://api.qrserver.com/v1/create-qr-code/?size=260x260&data='+v+'">'}
function color(){let h=$("#a").value.replace("#","");if(h.length===3)h=h.split("").map(function(x){return x+x}).join("");const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);out(JSON.stringify({hex:"#"+h.toUpperCase(),rgb:"rgb("+r+", "+g+", "+b+")",decimal:(r<<16)+(g<<8)+b},null,2))}
function timestamp(){const v=$("#a").value.trim(),d=/^\d{10,13}$/.test(v)?new Date(Number(v)<1e12?Number(v)*1000:Number(v)):new Date(v);out(isNaN(d)?"Invalid date":"ISO: "+d.toISOString()+"\nLocal: "+d.toString()+"\nUnix seconds: "+Math.floor(d.getTime()/1000))}
function regex(){try{const r=new RegExp($("#a").value,"g"),m=[...$("#b").value.matchAll(r)];out("Matches: "+m.length+"\n"+m.map(function(x){return x[0]}).join("\n"))}catch(e){out("Invalid regex: "+e.message)}}
function md(){let s=esc($("#a").value);s=s.replace(/^### (.*)$/gm,"<h3>$1</h3>").replace(/^## (.*)$/gm,"<h2>$1</h2>").replace(/^# (.*)$/gm,"<h1>$1</h1>").replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/\*(.*?)\*/g,"<em>$1</em>").replace(/\n/g,"<br>");$("#out").innerHTML=s}
function diff(){const a=$("#a").value.split("\n"),b=$("#b").value.split("\n"),n=Math.max(a.length,b.length);$("#out").innerHTML=Array.from({length:n},function(_,i){if(a[i]===b[i])return esc("  "+(a[i]||""));return '<span class="diff-del">'+esc("- "+(a[i]||""))+'</span>\n<span class="diff-add">'+esc("+ "+(b[i]||""))+"</span>"}).join("\n")}
function count(){const s=$("#a").value;out(JSON.stringify({words:(s.trim().match(/\S+/g)||[]).length,characters:s.length,charactersNoSpaces:s.replace(/\s/g,"").length,lines:s?s.split("\n").length:0},null,2))}
function compress(){const f=$("#a").files[0];if(!f)return out("Choose an image");const im=new Image,reader=new FileReader;reader.onload=function(){im.onload=function(){const c=document.createElement("canvas"),max=1800,scale=Math.min(1,max/Math.max(im.width,im.height));c.width=im.width*scale;c.height=im.height*scale;c.getContext("2d").drawImage(im,0,0,c.width,c.height);c.toBlob(function(b){out("Original: "+(f.size/1024).toFixed(1)+" KB\nCompressed: "+(b.size/1024).toFixed(1)+" KB")}, "image/jpeg",+$("#q").value)};im.src=reader.result};reader.readAsDataURL(f)}
function password(){const n=Math.max(4,Math.min(128,+$("#a").value||20)),chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*";const x=new Uint32Array(n);crypto.getRandomValues(x);out(Array.from(x,function(v){return chars[v%chars.length]}).join(""))}
async function hash(){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode($("#a").value));out([...new Uint8Array(h)].map(function(x){return x.toString(16).padStart(2,"0")}).join(""))}
function jwt(){try{const p=$("#a").value.split(".");if(p.length<2)throw Error("Expected a JWT");const dec=function(x){return JSON.parse(atob(x.replace(/-/g,"+").replace(/_/g,"/"))) };out("HEADER\n"+JSON.stringify(dec(p[0]),null,2)+"\n\nPAYLOAD\n"+JSON.stringify(dec(p[1]),null,2))}catch(e){out("Invalid JWT: "+e.message)}}
function ipcalc(){try{const z=$("#a").value.trim().split("/"),ip=z[0],bits=+z[1],o=ip.split(".").map(Number);if(bits<0||bits>32||o.length!==4)throw Error("Invalid IPv4/CIDR");const v=o.reduce(function(a,x){return (a<<8)+x},0)>>>0,mask=bits===0?0:(0xffffffff<<(32-bits))>>>0,net=(v&mask)>>>0,bc=(net|(~mask))>>>0,fmt=function(x){return [(x>>>24)&255,(x>>>16)&255,(x>>>8)&255,x&255].join(".")};out("Network: "+fmt(net)+"\nBroadcast: "+fmt(bc)+"\nMask: "+fmt(mask)+"\nAddresses: "+Math.pow(2,32-bits))}catch(e){out(e.message)}}
function cron(){const p=$("#a").value.trim().split(/\s+/);if(p.length!==5)return out("Use 5 fields: minute hour day-of-month month day-of-week");out(["Minute","Hour","Day of month","Month","Day of week"].map(function(x,i){return x+": "+p[i]}).join("\n")+"\n\n* = every value, */n = every n units, a-b = range, a,b = list")}
$("#themeBtn").onclick=function(){document.body.classList.toggle("dark");localStorage.theme=document.body.classList.contains("dark")?"dark":"light"};if(localStorage.theme==="dark")document.body.classList.add("dark");render();