using System.Globalization;
using System.IO.Compression;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
namespace RedroBridgeMaker;
static class VectorParser
{
 static double N(string s)=>double.Parse(s,CultureInfo.InvariantCulture);
 public static DocumentModel Load(string file)=>Path.GetExtension(file).ToLowerInvariant() switch{".eps"=>Eps(file),".svg"=>Svg(file),".pdf"=>Pdf(file),_=>throw new NotSupportedException("Use PDF, EPS or SVG.")};
 static DocumentModel Svg(string f){var d=new DocumentModel();var x=XDocument.Load(f);foreach(var el in x.Descendants().Where(e=>e.Name.LocalName=="path")){var q=Regex.Matches((string?)el.Attribute("d")??"",@"[MLmlHhVvZz]|-?\d+(?:\.\d+)?");double x0=0,y0=0;Pt? last=null;PathModel? p=null;foreach(Match m in q){var t=m.Value;if(t.Length==1&&!char.IsDigit(t[0])&&t[0]!='-'){if(t=="M"||t=="m"){var i=q.IndexOf(m);if(i+2<q.Count){x0=t=="M"?N(q[i+1].Value):x0+N(q[i+1].Value);y0=t=="M"?N(q[i+2].Value):y0+N(q[i+2].Value);p=new();p.Points.Add(last=new(x0,y0));d.Paths.Add(p);}}else if(t=="L"||t=="l"){ }else if(t=="Z"||t=="z"){p!.Closed=true;}}else if(p!=null&&last!=null){}}}return d;}
 static DocumentModel Eps(string f){var d=new DocumentModel();var text=File.ReadAllText(f);var tok=Regex.Matches(text,@"%.*$|[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?|/[A-Za-z]+|[A-Za-z]+",RegexOptions.Multiline);var st=new Stack<double>();PathModel? p=null;Pt cur=new(0,0);foreach(Match m in tok){if(m.Value.StartsWith("%"))continue;if(double.TryParse(m.Value,NumberStyles.Float,CultureInfo.InvariantCulture,out var n)){st.Push(n);continue;}var op=m.Value.TrimStart('/');if(op=="moveto"&&st.Count>=2){var y=st.Pop();var x=st.Pop();p=new();cur=new(x,y);p.Points.Add(cur);d.Paths.Add(p);}else if(op=="lineto"&&st.Count>=2&&p!=null){var y=st.Pop();var x=st.Pop();var q=new Pt(x,y);p.Segments.Add(new(cur,q));p.Points.Add(q);cur=q;}else if(op=="closepath"&&p!=null){p.Closed=true;}else if(op=="newpath"){p=null;}else if(op=="curveto"&&st.Count>=6&&p!=null){var y3=st.Pop();var x3=st.Pop();st.Pop();st.Pop();st.Pop();st.Pop();var q=new Pt(x3,y3);p.Segments.Add(new(cur,q));p.Points.Add(q);cur=q;}}return d;}
 static DocumentModel Pdf(string f){var d=new DocumentModel();var b=File.ReadAllBytes(f);var raw=Encoding.ASCII.GetString(b);foreach(Match m in Regex.Matches(raw,@"stream\r?\n(.*?)\r?\nendstream",RegexOptions.Singleline)){var bytes=Encoding.ASCII.GetBytes(m.Groups[1].Value);var s=m.Groups[1].Value;var deflated=s.Contains("/FlateDecode")?null:null;try{using var ms=new MemoryStream(bytes);using var z=new ZLibStream(ms,CompressionMode.Decompress);using var outMs=new MemoryStream();z.CopyTo(outMs);s=Encoding.ASCII.GetString(outMs.ToArray());}catch{}ParsePdfStream(s,d);}return d;}
 static void ParsePdfStream(string s,DocumentModel d){var tok=Regex.Matches(s,@"-?\d*\.?\d+|[A-Za-z]+|[hmlcSsnfBboxre]{1,2}");var st=new Stack<double>();PathModel? p=null;Pt cur=new(0,0);foreach(Match m in tok){if(double.TryParse(m.Value,NumberStyles.Float,CultureInfo.InvariantCulture,out var n)){st.Push(n);continue;}var op=m.Value;if(op=="m"&&st.Count>=2){var y=st.Pop();var x=st.Pop();p=new();cur=new(x,y);p.Points.Add(cur);d.Paths.Add(p);}else if(op=="l"&&st.Count>=2&&p!=null){var y=st.Pop();var x=st.Pop();var q=new Pt(x,y);p.Segments.Add(new(cur,q));p.Points.Add(q);cur=q;}else if(op=="re"&&st.Count>=4){var h=st.Pop();var w=st.Pop();var y=st.Pop();var x=st.Pop();p=new();var a=new Pt(x,y);var b=new Pt(x+w,y);var c=new Pt(x+w,y+h);var e=new Pt(x,y+h);p.Points.AddRange(new[]{a,b,c,e,a});p.Segments.AddRange(new[]{new(a,b),new(b,c),new(c,e),new(e,a)});p.Closed=true;cur=a;d.Paths.Add(p);}else if(op=="h"&&p!=null){p.Closed=true;}else if(op=="c"&&st.Count>=6&&p!=null){for(int i=0;i<4;i++){}var y3=st.Pop();var x3=st.Pop();st.Pop();st.Pop();st.Pop();st.Pop();var q=new Pt(x3,y3);p.Segments.Add(new(cur,q));p.Points.Add(q);cur=q;}}}
 static int IndexOf(this MatchCollection c,Match m){for(int i=0;i<c.Count;i++)if(c[i]==m)return i;return -1;}
}